[workspace]
resolver = "2"
members = ["games/mountaincar/*", "games/ringpong/*", "uilib", "rl"]

[workspace.package]
version = "0.1.0"
authors = ["Dylan Dronnier <dylan.dronnier@posteo.net>"]
description = "Playing dumb games with AI."
license = "MIT"
